# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: 📢 Binaries publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  version:
    name: 🚦 Update version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: jdx/mise-action@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            dry: true
      - if: steps.semrel.outputs.version != ''
        run: |
            git config user.name "forkboteu"
            git config user.email "apps@forkbomb.eu"
            echo ${{ steps.semrel.outputs.version }} > VERSION
            git add VERSION
            git commit -m "chore(pre-release): 🚀 update VERSION to ${{ steps.semrel.outputs.version }} [ci skip]"
            git push origin main

  release:
    name: 🔖 Release
    runs-on: ubuntu-latest
    needs: [version]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: main
      - uses: jdx/mise-action@v2
      - uses: sigstore/cosign-installer@v3.8.1
      - uses: anchore/sbom-action/download-syft@v0.18.0
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/attest-build-provenance@v2
        with:
          subject-checksums: ./dist/checksums.txt
